--- #YAML:1.0
name:               MogileFS-Plugin-FileRefs
version:            0.07
abstract:           MogileFS extension
author:
    - Dave Lambley <davel@state51.co.uk>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    MogileFS::Server:  0
    Test::More:        0
    Text::Exception:   0
resources:
    homepage:    https://metacpan.org/release/MogileFS-Plugin-FileRefs
    repository:  https://github.com/davel/MogileFS-Plugin-FileRefs
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
